spring.config.import=optional:file:.env[.properties]
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_SCHEMA}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=validate
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#BlockList
chaos.customers=666
#Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.cache.redis.ttl-minutes=1
logging.level.org.springframework.cache=TRACE