spring.config.import=optional:file:.env[.properties]
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_SCHEMA}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
