spring.config.import=optional:file:.env[.properties]
# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_SCHEMA}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=validate
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#Resilience4j
resilience4j.retry.instances.shippingRetry.max-attempts=3
resilience4j.retry.instances.shippingRetry.wait-duration=2s
resilience4j.retry.instances.shippingRetry.retry-exceptions=sube.interviews.mareoenvios.exception.RetryableIntegrationException
#BlockList
chaos.customer=666
